rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - limitranges
  - namespaces
  - resourcequotas
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingadmissionpolicies
  - validatingadmissionpolicybindings
  verbs:
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plume.dev
  resources:
  - agents
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - plume.dev
  resources:
  - agents/finalizers
  verbs:
  - update
- apiGroups:
  - plume.dev
  resources:
  - agents/status
  verbs:
  - get
  - patch
  - update
