// SPDX-FileCopyrightText: 2026 Quinyte
// SPDX-License-Identifier: Apache-2.0

package refgen

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	yaml "go.yaml.in/yaml/v3"
)

// Generate writes the three reference pages.
//
// Nothing here takes a timestamp, a hostname, a username or a path from the
// machine it runs on. That is not tidiness: `make verify` regenerates and
// compares, so any of those would make the check fail for everyone but whoever
// last committed — and a path would put the generating machine's filesystem
// into a public document.
func Generate(root, out string) error {
	if err := os.MkdirAll(out, 0o755); err != nil {
		return err
	}
	if err := checkSingleCRD(root); err != nil {
		return err
	}
	if err := renderCRD(root, out); err != nil {
		return err
	}
	if err := renderValues(root, out); err != nil {
		return err
	}
	return renderConditions(root, out)
}

// checkSingleCRD holds the claim crd-agent.md makes about its own scope.
//
// The page says Agent is the whole API surface. AGENTS.md rule 7 says never to
// state a bound the code does not enforce — so the generator enforces it: add a
// second CRD and generation fails here, naming the file, rather than publishing
// a page that describes one of two.
func checkSingleCRD(root string) error {
	dir := filepath.Join(root, "config", "crd")
	ents, err := os.ReadDir(dir)
	if err != nil {
		return fmt.Errorf("read %s: %w", dir, err)
	}
	var yamls []string
	for _, e := range ents {
		if !e.IsDir() && (strings.HasSuffix(e.Name(), ".yaml") || strings.HasSuffix(e.Name(), ".yml")) {
			yamls = append(yamls, e.Name())
		}
	}
	if len(yamls) != 1 || yamls[0] != filepath.Base(CRDSource) {
		return fmt.Errorf("docs/reference/crd-agent.md states that Agent is the whole API surface, "+
			"but config/crd holds %d CRD file(s): %s. Extend the generator to render them all, "+
			"and correct that sentence", len(yamls), strings.Join(yamls, ", "))
	}
	return nil
}

// frontMatter heads every page.
//
// It is here because a static site generator needs it: Astro's content
// collections — Starlight's schema among them — refuse a Markdown file with no
// `title`, so without this the pages cannot be published at all. Hand-adding a
// block would not survive, since `make reference` rewrites the file. Found by
// the independent review, which wired these pages into the site and got
// `InvalidContentEntryDataError ... title: Required`.
//
// There is deliberately NO in-body `# <title>` heading to go with it: a site
// renders the front-matter title as the page's heading, and a body H1 would
// show twice. GitHub renders the block itself, so the page is still titled when
// it is read in the repository.
//
// The values are QUOTED, which is the whole of the second attempt at this. The
// first emitted them as bare scalars, and one description contains ": " —
// "…custom resource: type, required…" — which YAML reads as a nested mapping
// key. The site build failed on it while `make reference`, `make verify` and
// `make unit` were all green, because reproducible invalid YAML is still
// reproducible and nothing here parsed what it wrote. The interaction problem
// had moved from "no front matter" to "invalid front matter", which reads as
// fixed and is worse. write() now parses every page before writing it.
func frontMatter(title, description string) string {
	return fmt.Sprintf("---\ntitle: %s\ndescription: %s\n---\n",
		yamlScalar(title), yamlScalar(description))
}

// yamlScalar renders a string as a YAML double-quoted scalar.
//
// Double quotes rather than single, so that a backslash and an embedded quote
// have defined escapes and nothing in a generated title can end the scalar
// early. Newlines and tabs are escaped rather than emitted, because a literal
// newline inside a quoted scalar changes what the document means.
func yamlScalar(s string) string {
	r := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		"\n", `\n`,
		"\r", `\r`,
		"\t", `\t`,
	)
	return `"` + r.Replace(s) + `"`
}

// generatedNotice tells a reader, and an editor, where the words actually come
// from. It names the command and the gate, so whoever was about to fix a typo
// here is told where the typo lives.
func generatedNotice() string {
	return "\n<!-- GENERATED FILE — DO NOT EDIT.\n" +
		"     Written by `make reference` (cmd/refgen).\n" +
		"     `make verify` regenerates it and fails if this file differs, so an edit here is\n" +
		"     reverted by CI rather than kept. Change the source, not the page. -->\n\n" +
		"> **Generated.** Do not edit this file. Run `make reference`; `make verify` fails if what is\n" +
		"> committed differs from a fresh generation.\n"
}

func write(path, body string) error {
	// A trailing newline and LF line endings, so that the committed file and a
	// fresh generation cannot differ over whitespace on someone's machine.
	body = strings.ReplaceAll(body, "\r\n", "\n")
	if !strings.HasSuffix(body, "\n") {
		body += "\n"
	}
	name := filepath.Base(path)
	if err := checkFrontMatter(name, body); err != nil {
		return err
	}
	if err := checkAnchors(name, body); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(body), 0o644)
}

// anchorDrop is everything GitHub's slugger removes from a heading.
//
// The algorithm is github-slugger's: lower-case, strip anything that is not a
// letter, a digit, a space, a hyphen or an underscore, then turn spaces into
// hyphens. An earlier version of this file replaced every run of non-alphanumeric
// characters with a hyphen, which produced `gateway-enabled` for a heading
// GitHub slugs as `gatewayenabled` — so every link in the chart index was dead,
// on GitHub, in the committed page. Found by the independent review.
var anchorDrop = regexp.MustCompile(`[^a-z0-9 _-]+`)

// anchor is the heading-anchor form of a heading's text.
func anchor(s string) string {
	s = strings.ToLower(s)
	s = anchorDrop.ReplaceAllString(s, "")
	return strings.ReplaceAll(s, " ", "-")
}

var (
	headingLine  = regexp.MustCompile(`(?m)^(#{1,6})[ \t]+(.+?)[ \t]*$`)
	mdLink       = regexp.MustCompile(`\]\(#([^)\s]+)\)`)
	htmlAnchor   = regexp.MustCompile(`(?i)<a[^>]+href="#([^"]+)"`)
	htmlIDAttr   = regexp.MustCompile(`(?i)\bid="([^"]+)"`)
	inlineFormat = regexp.MustCompile("[`*_]")
	fencedBlock  = regexp.MustCompile("(?s)```.*?```")
)

// FrontMatter parses a page's YAML front matter, the way a static site
// generator's content loader does.
//
// It is exported so that the gate inside the generator and any check outside it
// are the same parse, and it returns the decoded map so a caller can ask what
// is in it rather than only whether it scanned.
func FrontMatter(body string) (map[string]any, error) {
	const fence = "---\n"
	if !strings.HasPrefix(body, fence) {
		return nil, fmt.Errorf("the page has no front matter: an Astro content collection — " +
			"Starlight's schema among them — refuses a Markdown file without one")
	}
	rest := body[len(fence):]
	end := strings.Index(rest, "\n"+fence)
	if end < 0 {
		return nil, fmt.Errorf("the front matter block is never closed by a `---` line")
	}
	var out map[string]any
	if err := yaml.Unmarshal([]byte(rest[:end+1]), &out); err != nil {
		return nil, fmt.Errorf("the front matter is not valid YAML: %w", err)
	}
	return out, nil
}

// checkFrontMatter refuses to write a page whose front matter a site cannot
// load. Reproducible invalid YAML is still invalid: nothing else in this
// repository parses it, so without this the only thing that catches it is a
// docs-site build in another repository.
func checkFrontMatter(name, body string) error {
	fm, err := FrontMatter(body)
	if err != nil {
		return fmt.Errorf("%s would have been written with front matter no site can load: %w", name, err)
	}
	title, _ := fm["title"].(string)
	if strings.TrimSpace(title) == "" {
		return fmt.Errorf("%s would have been written with no `title` in its front matter, which is "+
			"the one field an Astro content collection requires", name)
	}
	return nil
}

// pageAnchors is every in-page target a renderer would create for a document:
// a slug per heading, plus any explicit HTML id. A heading whose slug is already
// taken gets the `-1`, `-2` suffixes a renderer appends, and the second return
// value names the headings that needed one.
//
// Fenced code is removed first. A heading or a link inside a fence is text, not
// navigation, and counting it would invent targets that do not exist.
func pageAnchors(body string) (have map[string]bool, duplicated []string) {
	body = fencedBlock.ReplaceAllString(body, "")
	have = map[string]bool{}
	seen := map[string]int{}
	for _, m := range headingLine.FindAllStringSubmatch(body, -1) {
		slug := anchor(inlineFormat.ReplaceAllString(m[2], ""))
		if slug == "" {
			continue
		}
		if n := seen[slug]; n > 0 {
			duplicated = append(duplicated, m[2])
			have[fmt.Sprintf("%s-%d", slug, n)] = true
		}
		seen[slug]++
		have[slug] = true
	}
	for _, m := range htmlIDAttr.FindAllStringSubmatch(body, -1) {
		have[strings.ToLower(m[1])] = true
	}
	return have, duplicated
}

// DeadAnchors returns the in-page links a document makes that land nowhere.
//
// It is exported so that the gate over the whole docs tree and the gate inside
// this generator are the SAME algorithm. Two implementations of "does this link
// land" would be one more pair of copies that drift, which is the thing this
// package exists to stop.
func DeadAnchors(body string) []string {
	have, _ := pageAnchors(body)
	body = fencedBlock.ReplaceAllString(body, "")
	seen := map[string]bool{}
	var dead []string
	for _, re := range []*regexp.Regexp{mdLink, htmlAnchor} {
		for _, m := range re.FindAllStringSubmatch(body, -1) {
			target := strings.ToLower(m[1])
			if have[target] || seen[target] {
				continue
			}
			seen[target] = true
			dead = append(dead, target)
		}
	}
	return dead
}

// checkAnchors refuses to write a page whose own links do not land.
//
// Every in-page link in these files is emitted by this generator, so a dead one
// is a generator bug and belongs here rather than in a reviewer's browser. The
// first version shipped 51 of them — 23 index entries for condition types that
// got no section, and 28 chart keys slugged by an algorithm no renderer uses.
//
// A GENERATED page is also refused for two headings that slug alike. A renderer
// disambiguates the second with a `-1` suffix, so the links still land, but the
// generator has no business emitting a collision it can simply not emit — and
// the first attempt at the CEL section collided with seven of crdoc's headings.
func checkAnchors(name, body string) error {
	_, dupes := pageAnchors(body)
	dead := DeadAnchors(body)

	var problems []string
	if len(dead) > 0 {
		problems = append(problems, fmt.Sprintf("%d link(s) point at an anchor the page does not "+
			"have: #%s", len(dead), strings.Join(dead, ", #")))
	}
	if len(dupes) > 0 {
		problems = append(problems, fmt.Sprintf("%d heading(s) slug to an anchor another heading "+
			"already took, so a reader following a link to one lands on the other: %s",
			len(dupes), strings.Join(dupes, ", ")))
	}
	if len(problems) > 0 {
		return fmt.Errorf("%s would have been written with broken navigation:\n  %s",
			name, strings.Join(problems, "\n  "))
	}
	return nil
}
