// SPDX-FileCopyrightText: 2026 Quinyte
// SPDX-License-Identifier: Apache-2.0

package refgen

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// Generate writes the three reference pages.
//
// Nothing here takes a timestamp, a hostname, a username or a path from the
// machine it runs on. That is not tidiness: `make verify` regenerates and
// compares, so any of those would make the check fail for everyone but whoever
// last committed — and a path would put the generating machine's filesystem
// into a public document.
func Generate(root, out string) error {
	if err := os.MkdirAll(out, 0o755); err != nil {
		return err
	}
	if err := checkSingleCRD(root); err != nil {
		return err
	}
	if err := renderCRD(root, out); err != nil {
		return err
	}
	if err := renderValues(root, out); err != nil {
		return err
	}
	return renderConditions(root, out)
}

// checkSingleCRD holds the claim crd-agent.md makes about its own scope.
//
// The page says Agent is the whole API surface. AGENTS.md rule 7 says never to
// state a bound the code does not enforce — so the generator enforces it: add a
// second CRD and generation fails here, naming the file, rather than publishing
// a page that describes one of two.
func checkSingleCRD(root string) error {
	dir := filepath.Join(root, "config", "crd")
	ents, err := os.ReadDir(dir)
	if err != nil {
		return fmt.Errorf("read %s: %w", dir, err)
	}
	var yamls []string
	for _, e := range ents {
		if !e.IsDir() && (strings.HasSuffix(e.Name(), ".yaml") || strings.HasSuffix(e.Name(), ".yml")) {
			yamls = append(yamls, e.Name())
		}
	}
	if len(yamls) != 1 || yamls[0] != filepath.Base(CRDSource) {
		return fmt.Errorf("docs/reference/crd-agent.md states that Agent is the whole API surface, "+
			"but config/crd holds %d CRD file(s): %s. Extend the generator to render them all, "+
			"and correct that sentence", len(yamls), strings.Join(yamls, ", "))
	}
	return nil
}

// generatedNotice heads every page. It names the command and the inputs so that
// a reader who doubts a line knows exactly what to read instead, and an editor
// who was about to fix a typo here is told where the typo actually lives.
func header(title string) string {
	return fmt.Sprintf(`<!-- GENERATED FILE — DO NOT EDIT.
     Written by `+"`make reference`"+` (cmd/refgen).
     `+"`make verify`"+` regenerates it and fails if this file differs, so an edit here is
     reverted by CI rather than kept. Change the source, not the page. -->

# %s

> **Generated.** Do not edit this file. Run `+"`make reference`"+`; `+"`make verify`"+` fails if what is
> committed differs from a fresh generation.
`, title)
}

func write(path, body string) error {
	// A trailing newline and LF line endings, so that the committed file and a
	// fresh generation cannot differ over whitespace on someone's machine.
	body = strings.ReplaceAll(body, "\r\n", "\n")
	if !strings.HasSuffix(body, "\n") {
		body += "\n"
	}
	return os.WriteFile(path, []byte(body), 0o644)
}

var nonAnchor = regexp.MustCompile(`[^a-z0-9]+`)

// anchor is the GitHub heading-anchor form of a string.
func anchor(s string) string {
	return strings.Trim(nonAnchor.ReplaceAllString(strings.ToLower(s), "-"), "-")
}
